spring:
  application:
    name: mszhan-redwine-manage-server

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    sumptuousManage:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sumptuous_manage?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
      username: root
      password: root

      max-active: 50
      min-idle: 10
      initial-size: 10
      max-wait: 10000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 20000

  thymeleaf:
    cache: false
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
    suffix: .html
  mvc:
    throw-exception-if-no-handler-found: true
server:
  port: 8081
  error:
    include-stacktrace: always
    path: /page/error
